### ISSUE TITLE
Can't figure out how to get this to work? 

### ISSUE THREAD

**Issue by fiveseven808** [Veldrovive/MMM-Page-Selector#1]
So, I copied 
```
{
        module: "MMM-Page-Selector",
        position: "top_bar",
        config: {
            page: "pageName",
            displayTitle: true,
        }
    },
```

into my config.js, but whenever I add `pages:"all",` to my modules, magicmirror doesn't seem to want to start up... Not sure what I'm doing wrong, or how to get names and pages into this thing in the first place?

**Comment by Veldrovive** [comment]
Sorry it took me so long to get back to you. 
Where are you putting the `pages: "all"`?
Do the pages work correctly if you do not use the all option?
Are you getting any errors in your console?

**Comment by justjim1220** [comment]
my question is where and how do I configure the page index to give each page a different name or title?

**Comment by Veldrovive** [comment]
I'm not sure I know exactly what you mean. If the question is `How do I assign a given page to a certain index?` then the answer is that I didn't really think about that because the module originally worked differently. To do it in a more hacky way, pages that are declared first (so higher up in the config file) should be pushed into the page object first, but that is no guarantee that they will maintain their position. If this is the question you are asking, I can add a new section in the page selector config to add the functionality.

If your question about more general usage, here is a more concise version of the readme.
To tell a module to appear on a certain page, add <br/>`pages: {"PAGE_NAME": "POSITION"}` under the standard position prop in the module's config. Then, to switch pages, I would use [MMM-page-indicator](https://github.com/edward-shen/MMM-page-indicator), [MMM-Voice-Commands](https://github.com/Veldrovive/MMM-Voice-Commands) or any other module that can be configured to send notifications.

**Comment by justjim1220** [comment]
ok, this is from your ReadMe file...

```
    //Example of the config for a module to be shown on pages: "main" and "fun"
    {
        module: "MMM-any-other",
        position: "bottom_center", //Or any other position, this doesnt matter unless "pages" is set to "all"
        pages: {"main": "position", "fun": "another_position"},
        config: {}
    },
  ```

What I'm asking is how do you name the pages as "main" & "fun", etc. ???

**Comment by justjim1220** [comment]
there isn't anything in your ReadMe regarding naming the pages

**Comment by justjim1220** [comment]
you have this for the cinfiguration of the module...

```
{
        module: "MMM-Page-Selector",
        position: "top_bar",
        config: {
            page: "pageName",
            displayTitle: true,
        }
    },
```

which allows me to name 1 page. Which is fine. But then how do I get it to change pages if I can't name them?
when I try to make an array within that code it throws an error with the config.js file
I've tried a few ways, and not getting anywhere.

like this...
```
 {
            module: "MMM-Page-Selector",
            position: "bottom_bar",
            pages: "all",
            config: {
                page: {"1": "Page 1", "2": "Page 2", "3": "Page 3", "4": "Page 4"},
                displayTitle: true,
            }
        },
```
and this...
 {
            module: "MMM-Page-Selector",
            position: "bottom_bar",
            pages: "all",
            config: {
                page: {"1": "Main Page", "2": "Football", "3": "Email & Shit", "4": "Misc"},
                displayTitle: true,
            }
        },
```
and this...
 {
            module: "MMM-Page-Selector",
            position: "bottom_bar",
            pages: "all",
            config: {
                page: {"0": "One", "1": "Two", "2": "Three", "3": "Page Four"},
                displayTitle: true,
            }
        },
```
and this...
```
{
            module: "MMM-Page-Selector",
            position: "bottom_bar",
            pages: "all",
            config: {
                page: {"1": "One", "2": "Two", "3": "Three", "4": "Page Four"},
                displayTitle: true,
            }
        },
```

**Comment by Veldrovive** [comment]
And to be clear, pages are never explicitly defined. They are simply created by assigning a module to appear on that page.

**Comment by Veldrovive** [comment]
I changed the README to make the usage more clear. I'm going to close this issue as I believe that it has been resolved, but if there is further confusion on general usage then feel free to re-open.

**Comment by cowboysdude** [comment]
Going by this example:  
`
modules: [
    {
        module: "MMM-Page-Selector",
        position: "top_center",
        config: {
            page: "main"
            displayTitle: true
        }
    },
    {
        module: "MMM-Weather-Now",
        position: "bottom_center",
        pages: {main: "top_right", weather: "bottom_left"}
    },
    {
        module: "MMM-page-indicator",
        position: "bottom_center",
        pages: "all"
    }
]
`
All that happens is that you are saying on page 'main' go to 'top_right'......on page weather go to 'bottom_left'......  

When I start the mirror I set main as the start page and I have page-indicator running too.   No matter what page I start on 'main' or 'weather' the weather shows 'top_right' and I cannot access the other page at all.

Cannot figure out how to make this work........

**Comment by Veldrovive** [comment]
There are a couple of things that are going to be causing problems with new versions. I'm trying not to make any changes that break old configs, but in a couple of cases, it's pretty much unavoidable due to internal ways the module works.

First, in the dev branch that will be merged in a couple days, the `page` config key has been completely replaced by `defaultPage` to reduce confusion about what that prop does.

Second, to assign a module to be on all pages, you no longer just specify `pages: "all"`, instead, use the same format as normal pages except have the page name be "all": `pages: {"all": "bottom_center"}`.

Third, it is no longer necessary to specify a position for every module but page-selector. It doesn't do any harm to have them, but you don't have to.

Here is the config with all those changes (For the most updated version of page-selector):
```js
modules: [ 
    { 
        module: "MMM-Page-Selector", 
        config: { 
            defaultPage: "main", 
            displayTitle: true
        }
    },
    { 
        module: "MMM-Weather-Now", 
        pages: {
            main: "top_right", 
            weather: "bottom_left" 
        },
    },
    { 
        module: "MMM-page-indicator", 
        pages: {"all" : "bottom_center"}
    } 
]
```

**Comment by cowboysdude** [comment]
I appreciate the input.   I'll try the dev branch.  What I see was happening is I'm mixing the master branch with dev branch config.......that'll cause a problem.  So I'll go try the dev branch and see if that works for me :)  By the way this is a REALLY great module!!

**Comment by Veldrovive** [comment]
Can you tell me exactly what is happening? 
When you say that you cannot see or rotate to the other page, do you mean that when you navigate to the next page, the DOM does not change?
Or do you mean that you are unable to navigate to the next page in the first place?

**Comment by cowboysdude** [comment]
Yes I am unable to navigate to the next page in the first place

**Comment by Veldrovive** [comment]
Ok, Page-Selector does not handle navigation in-house.
I always suggest using MMM-page-indicator since when you click on one of the circles at the bottom it will navigate to that page. To keep the cursor visible so you can actual click on them I suggest [MMM-Cursor](https://github.com/MarinescuEvghenii/MMM-Cursor).
The other main option is to use one of the many voice command modules. I, of course, use my own ([MMM-Voice-Commands](https://github.com/Veldrovive/MMM-Voice-Commands#usage-with-external-modules)), but its functionality is very limited to exactly what I need. Any of the other ones should be able to integrate pretty well too.

**Comment by justjim1220** [comment]
@cowboysdude 
Here is how mine turns out:
First my config.js:
`
modules: [
		{
			module: "MMM-Page-Selector",
			position: "top_right",
			config: {
				defaultPage: "Main",
				displayTitle: true
			}
		},

		{
			module: "MMM-page-indicator",
			pages: { "all": "top_left"},
			config: {
				pages: 3,
				activeBright: true,
				inactiveHollow: true
			}
		},

		{
			module: "MMM-Cursor",
			config: {
				timeout: 1000
			}
		},

		{
			disabled: false,
			module: "MMM-BMW-DS",
			position: "top_bar",
			pages: { "Main": "Middle_center", "Two": "bottom_bar", "Three": "top_bar" },
			config: {
				apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
				tempUnits: "F",
				lat: "40.26189",
				lng: "-94.03534",
				css: "1",
				ownTitle: "Current Weather Conditions for Bethany, MO:", // Default = Current Conditions
				playSounds: "yes", // yes = weather sounds, no = no weather sounds
				useHeader: false, // true if you want a header
				header: "Your Header", // Any text you want. useHeader must be true
				maxWidth: "100%",
				animationSpeed: 3000,
				initialLoadDelay: 1500,
				retryDelay: 2000,
				updateInterval: 15 * 60 * 1000,
			}
		},

		{
			disabled: false,
			module: "MMM-DigClock",
			position: "top_right",
			pages: { "Main": "top_right", "Two": "top_center", "Three": "middle_center" },
			config: {
				showDate: false,
				showWeek: false,
			}
		},

		{
			disabled: false,
			module: "MMM-PC-Stats",
			position: "top_left",
			pages: { "Main": "top_left", "Two": "bottom_center"},
			config: {
				videoCard: "NVIDIA GeForce GTX 960M",
				useHeader: true,
				header: "My PC Stats...",
				animationSpeed: 0,
				updateInterval: 3 * 1000
			}
		},

		{
			disabled: false,
			module: "MMM-NewsFeedTicker",
			position: "bottom_bar",
			pages: { "Main": "top_bar", "Two": "Middle_center", "Three": "bottom_bar" },
			config: {
				feeds: [
					{
						title: "NFL News",
						url: "https://www.rotowire.com/rss/news.htm?sport=nfl",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "ESPN NFL News",
						url: "http://www.espn.com/espn/rss/nfl/news",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "Kansas City Fox Sports News",
						url: "https://api.foxsports.com/v1/rss?partnerKey=zBaFxRyGKCfxBagJG9b8pqLyndmvo7UU&tag=kansas-city",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "CBC Canada NFL News",
						url: "https://www.cbc.ca/cmlink/rss-sports-nfl",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "USA Today NFL News",
						url: "http://rssfeeds.usatoday.com/UsatodaycomNfl-TopStories",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "Fox Sports NFL News",
						url: "https://api.foxsports.com/v1/rss?partnerKey=zBaFxRyGKCfxBagJG9b8pqLyndmvo7UU&tag=nfl",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "CBS Sports NFL Headlines",
						url: "https://www.cbssports.com/rss/headlines/nfl/",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "Wall St. Journal",
						url: "http://www.wsj.com/xml/rss/3_7455.xml",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "Washington Post",
						alt: "Washington Post",
						url: "http://feeds.washingtonpost.com/rss/rss_comic-riffs",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "BBC World News",
						url: "http://feeds.bbci.co.uk/news/world/rss.xml#",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						defaultLogo: ""
					},
					{
						title: "NBC Sports-Network",
						url: "https://profootballtalk.nbcsports.com/feed/atom/",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						customLogo: "modules/MMM-NewsFeedTicker/pics/NBCSports"
					},
					{
						title: "Sports Illustrated",
						url: "https://www.si.com/rss/si_nfl.rss",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						customLogo: "modules/MMM-NewsFeedTicker/pics/SI2.png"
					},
					{
						title: "KC Chiefs News",
						url: "https://www.kansascity.com/sports/nfl/kansas-city-chiefs/",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						customLogo: "modules/MMM-NewsFeedTicker/pics/KCChiefsNews"
					},
					{
						title: "Bethany Republican Clipper",
						url: "https://www.bethanyclipper.com/category/breaking/",
						encoding: "UTF-8", //ISO-8859-1
						className: "myClass",
						customLogo: "modules/MMM-NewsFeedTicker/pics/BethanyRepublicanClipper"
					}
				]
			}
		}
	]
`

Now, "Main" page:
![screenshot 432](https://user-images.githubusercontent.com/27590633/48883032-5e48f980-ede3-11e8-9fd3-7a93cd19cdad.png)

page "Two":
![screenshot 431](https://user-images.githubusercontent.com/27590633/48883051-7caef500-ede3-11e8-9de1-8cf6053a7e50.png)

page "Three":
![screenshot 430](https://user-images.githubusercontent.com/27590633/48883055-889ab700-ede3-11e8-8001-ea31de652215.png)

As you can see, nothing comes out right...
But, for what I am wanting to do, I didn't really need to have duplicates of the same module on different pages, unless it was on all the pages.

So, for me, it was easier to use MMM-pages instead

**Comment by cowboysdude** [comment]
I will try MMM-Cursor tomorrow........ I use MMM-voice [I helped him when
he was developing it]  I did try MMM-Voice-Commands but I couldn't get it
to work.  I am not running on a pi I am running a 32" touch screen on a
real mini itx computer ;)

**Comment by justjim1220** [comment]
at the moment, I haven't been able to get the Voice commands to work with Windows, which is what I use.
I found something that I think will help me get it to work, I just need to dive into it and try, Haven't been doing much with MM as of late, been down with health, and busy.

So, that is why I use MMM-Cursor so I can navigate through the pages using the MMM-page-indicator.

At the moment, I am using my test, or dev machine, so my main MM isn't on here, so what you are seeing in the pics are what is on my test MM at the moment.

But wanted to show you how I was able to get it to work (somewhat) but by what I was meaning that I couldn't get it to work right as stated in the forums chat.

**Comment by cowboysdude** [comment]
You won't be able to get voice commands to work with windows......it's windows.  You need unbuntu or some other type of Linux variant.   As for this module it's not working for me...... I tried both the dev and master and it just isn't working.   I'm pretty knowledgeable about js and I'm capable of following directions but this doesn't work.  When I try to use it with MMM-voice it throws errors and voice won't load......  It's like any other module.  If you're the writer it's easy for you but it's not always easy for the non writer to figure out what's going on.  I appreciate the module and it took work but if it's not going to work then I can't waste a week trying to get it working either.

**Comment by cowboysdude** [comment]
OK just so I don't leave anyone hanging...... I put this in my custom.css file and it solved the issue for 👍 
      .fullscreen.above {
	  z-index: -1
        }

NOW I can click on the indicator and it works ;)
