### ISSUE TITLE
Ordering of modules

### ISSUE THREAD

**Issue by burberius** [Veldrovive/MMM-Page-Selector#11]
I just changed my mirror to use _MMM-Page-Selector_ with the first configuration version.
Now all modules that have the same position are ordered the other way around.
In my config I have something like:
```
Module1 -> top_left
Module2 -> top_left
Module3 -> top_left
```
Without _MMM-Page-Selector_ they are in the order of numbering.

With _MMM-Page-Selector_ they are in ordered the other way around:
* 3
* 2
* 1

Do I have to reorder all my modules now?

**Comment by Veldrovive** [comment]
Right, I forgot about this issue. Thanks for reminding me. I can have it fixed tomorrow.

**Comment by Veldrovive** [comment]
Sorry, that took me a bit longer to get to than expected.
The issue should be fixed as of commit 5d73021, but you have to be in the development branch to get the changes since I changed a large amount of potentially module breaking code.
The ordering of modules now makes intuitive sense using both methods described in the readme.

**Comment by burberius** [comment]
Works perfect, thank you.

**Comment by burberius** [comment]
It doesn't... :-(

I found a case were it doesn't work:
```
                {
                        module: "MMM-wiki",
                        pages: {"special": "bottom_bar"},
                        position: "bottom_bar",
                        ...
                },
                {
                        module: "newsfeed",
                        pages: {"all": "bottom_bar"},
                        position: "bottom_bar",
                        ...
                },
                {
                        module: 'random_quotes',
                        pages: {"all": "bottom_bar"},
                        position: 'bottom_bar',
                        ...
                }
```
When it shows the special page, the order is:
1. newsfeed
2. random_quotes
3. MMM-wiki

**Comment by Veldrovive** [comment]
Ah right. I didn't think about the case where exclusions and pages interact. I'll have that one fixed soon.

**Comment by Robiv8** [comment]
i have the same issue

**Comment by GoodWillGustin** [comment]
Sounds kinda like the modules are rendering globally then page-specific. Meaning that if you changed the ones that are "pages: {all: "position"} to each page at that position, you might get different results. They might then render individually, in order, rather than carrying over from the inital load.

**Comment by GoodWillGustin** [comment]
> @Veldrovive @burberius
> 
> It seems like that I met the same problem.
> In page 0, the newsfeed module is on top of the MMM-page-indicator module. It's unconventional.
> ![image](https://user-images.githubusercontent.com/48181152/55804997-1f0c1280-5b10-11e9-97f2-d62a5fbbee70.png)
> 
> I hope the layout of page 0 is same as page 3:
> ![image](https://user-images.githubusercontent.com/48181152/55805075-46fb7600-5b10-11e9-9d36-a23d2cb6cc6a.png)
> 
> No matter how I adjust the order of these modules, the MMM-page-indicator position is always on bottom of screen.
> 
> Could you give me some suggestion? Thanks in advance.

Sounds kinda like the modules are rendering globally then page-specific. Meaning that if you changed the ones that are "pages: {all: "position"} to each page at that position, you might get different results. They might then render individually, in order, rather than carrying over from the inital load.

**Comment by Veldrovive** [comment]
Well, it's been a bit, but I just fixed this while I was working out another bug. Exclusions now always render after moving modules.
