### ISSUE TITLE
How to display the same module in different forms in different pages.

### ISSUE THREAD

**Issue by wangjiwang** [Veldrovive/MMM-Page-Selector#15]
hi, Veldrovive. Thanks for your module.  There is a problem, when I show some modules in the main page, the module is too small to see. So I want to zoom in these modules in the new pages. Look forward your reply.

**Comment by Veldrovive** [comment]
Hello, I am a bit unclear on what the problem is. Do you want to size modules differently depending on what page they are on? If that is the case, I have a potential solution. On the `development` branch, when pages are switched, the css class `page_{current_page}` is added to the module so modules can look different on different pages. 
If you give module names and descriptions of the expected results, I can advise on what specifically to put in your custom css.

**Comment by wangjiwang** [comment]
hi, Yes, I want to  size modules differently depending on what page they
are on. There are six pages in total，main, work, life, email,conclusion and
news as attached. Please note that the red letters on the picture are
comments for you, pages don not show them. So I divide the main page into
five parts, they are  work, life, email, conclusion and news page. I want
to zoom in those modules in five pages.

I am sorry, the content on the page is displayed in Chinese.

Aidan Dempster <notifications@github.com> 于2019年1月27日周日 上午3:05写道：
