### ISSUE TITLE
change pages with one physical button

### ISSUE THREAD

**Issue by GattoJohnny** [Veldrovive/MMM-Page-Selector#16]
Dear Aidan,

I really like MMM-Page-Selector for its nice feature of allowing to display the same module on different pages with different layout and configuration. I use [MMM-Buttons] to handle the key presses, but unlike Robiv8 in Issue#7 I have one single button on my mirror rather than separate buttons for each page. 
As I learned other modules can send notifications to "PAGE_SELECT" with a payload of either the page name or of the page index. Is it possible to add the feature to accept "next" and "previous" in the payload? That way I could pass these information with short and long presses.

Cheers, Gyorgy

**Comment by Veldrovive** [comment]
If I understand what you are asking for, this feature is already included in the module. 
In order to go to the next page, you can send a notification to `INCREMENT_PAGE` and to go to the previous page, send a notification to `DECREMENT_PAGE`. Just like with `PAGE_SELECT`, you can also change these notifications to be whatever you want as described in the [Usage](https://github.com/Veldrovive/MMM-Page-Selector#usage) section of the readme in the second example.

**Comment by GattoJohnny** [comment]
Oh, that's it, indeed. Thanks for the quick reply. :-)
