### ISSUE TITLE
Commands with functions

### ISSUE THREAD

**Issue by djfattius** [Veldrovive/MMM-Page-Selector#22]
Veldrovive-

Great job on Voice-Commands and Page-Selector.  I don't know if this issue is with Voice-Commands for Page-Selector.  So I will start here.

I cannot get voice commands with a function to work.  I did some debug and I see that any commands that includes functions are not written out to the temp config.js created by Page Selector.  I do not know if my syntax for creating the function is wrong and Page Selector doesn't recognize it, or if there is an issue with page selector.

Sample from original config.js:
```
commands: {
    "the eagle is on *page": "PAGE_SELECT",
    "Go to page *pagename": function(param){ 
        this.sendNotifications("PAGE_SELECT", param);
    }
}
```
Sample from temp config.js created by Page Selector:
```
"commands": {
    "the eagle is on *page": "PAGE_SELECT"
}
```
Full sample uploaded.

[config.js.txt](https://github.com/Veldrovive/MMM-Voice-Commands/files/3721361/config.js.txt)

I'm sure I'm crazy or using bad syntax.  I simply can't get the config.js created by Page Selector to show any commands with functions.

Your input is greatly appreciated.

DJ Fattius

**Comment by Veldrovive** [comment]
Hey,
I updated the module so this wouldn't be an issue. If you get the latest commit, it should work even if you having functions in your config.js.

What happened under the hood is that I specified a new way to transform the json into a string that also serializes functions so that the temp config is an exact copy of the original config just with position props added.

**Comment by djfattius** [comment]
Hey Veldrovive-

It works great!  Thanks for the quick turn-around!

DJ Fattius
