### ISSUE TITLE
MMM-WatchDog Restart Loop

### ISSUE THREAD

**Issue by Veldrovive** [Veldrovive/MMM-Page-Selector#8]
When MMM-WatchDog is included and the `position` prop for modules are not set, WatchDog triggers a shutdown and PM2 restarts MM which then causes a restart loop.
This seems to be due to the restart the Page-Selector triggers when it finds modules that don't have positions.

**Comment by fnsign** [comment]
Hi! 
Has this issuen been solved? Or is a workaround available?
I'm running into the same issue, that MM constantly restarts a few times and then stops completely. I also have a few modules which have no position prop (e.g. MMM-PIR-Sensor, alert, MMM-Button, MMM-Podcast2, just to name a few).
It stops because Pageselector obviously deletes the config.js. in the config folder then I find instead a file called config.page-selector.temp.js.

**Comment by Veldrovive** [comment]
I have not found a fix for this issue and I fear there is no easy fix since the modules are well and truly at odds in the way they function. Increasing the `timeout` might help by making the interval between pings short enough that the restart is not detected as a crash.
The more feasible workaround is to simply define a default position for all modules. That way the mirror never restarts itself in the first place.

**Comment by fnsign** [comment]
Thanks for replying!
I'll try the workaround you described.

**Comment by GoodWillGustin** [comment]
> Thanks for replying!
> I'll try the workaround you described.

Did that work for you? I just installed this module and am running into the same issue with Watchdog crashing after 10 minutes.

**Comment by fnsign** [comment]
> Did that work for you?

Unfortunately not. I am currently using a different page switcher module.

**Comment by Veldrovive** [comment]
Sorry I never got back to you. I've mostly stopped development on this module and just check back in every once in a while to help. Since this issue is so old, I'm just going to close it.

If you still use the module and have a problem you can open a new issue. I have a few days where I can work some stuff out.
